server.port: ${gateway.server.port}

token.sign.key: token.2018.03.23
token.expire.minutes: 60

spring:
  application:
    version: v1
    cnname: dbus网关-v1
    name: dbus-keeper-gateway-${spring.application.version}
  messages:
    cache-seconds: 3600
    encoding: UTF-8
    basename: i18n/messages
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl.defaultZone: ${register.server.url}

zuul:
  ignoredPatterns: /**/login
  routes:
    keeper-service:
      path: /v1/keeper/keeper-service/**
      serviceId: dbus-keeper-service-v1
    keeper-mgr:
      path: /v1/keeper/**
      serviceId: dbus-keeper-mgr-v1
  sensitive-headers:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 30000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
