highlighter: pygments
markdown: kramdown
plugins:
  - jekyll-redirect-from

kramdown:
  entity_output: numeric

include:
  - _static
  - _modules

DBUS_VERSION_SHORT: 0.6.0
SCALA_BINARY_VERSION: "2.11"
SCALA_VERSION: "2.11.8"
